version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/linux_env
    command: sleep infinity
    network_mode: service:postgres
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@localhost:5432/whatsapp_ai
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_NAME=whatsapp_ai

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: whatsapp_ai
    ports:
      - "5432:5432"

volumes:
  postgres-data:

