# Rolling Features Configuration - Simplified
rolling_features:
  # Window sizes (in days) - easily configurable
  windows:
    short_term: 14    # 2 weeks
    medium_term: 28   # 4 weeks
    long_term: 56     # 8 weeks

  # Amount features with dynamic naming
  amount_features:
    amt_1_std_2w:
      base_column: "amt_1"
      window: "short_term"  # Uses 28 days from windows config
      operation: "std"

    amt_1_2w:
      base_column: "amt_1"
      window: "short_term"  # Uses 28 days from windows config
      operation: "sum"

  # Transaction features
  transaction_features:
    drop_vs_max: true
    no_txn_today: true
    days_without_txn_2w:
      window: "short_term"  # Uses 56 days from windows config

  # Features to extract for final dataset
  extract_features:
    - "amt_1_std_2w"
    - "txn_drop_vs_max"
    - "amt_1_2w"
    - "days_without_txn_2w"
